version: "3"

services:
  mongo:
    image: mongo:3.6.21-xenial
    container_name: find-bike-db
    ports:
      - 27017:27017
    networks:
      - find-bike
    volumes:
      - data/db

  api-server:
    image: docker.io/juxhinbleta/find-bike:1.0.0
    container_name: find-bike-app
    ports:
      - 7777:7777
    depends_on:
      - mongo
    networks:
      - find-bike

networks:
  find-bike:
    driver: bridge

volumes:
  mongo-data:
    driver: local
