version: "3"

services:
  api-server:
    image: docker.io/juxhinbleta/find-bike:1.0.0
    environment:
      - 
    ports:
      - 4000:4000
    depends_on:
      - mongo
    networks:
      - find-bike

  mongo:
    image: mongo:3.6.21-xenial
    environment:
      - 
    ports:
      - 27017:27017
    networks:
      - find-bike
    volumes:
      - mongo-data:data/db

networks:
  find-bike:
    driver: bridge

volumes:
  mongo-data:
    driver: local
